---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность зайти на сайт через аккаунты GitHub или Discord
  - Пользователь должен иметь возможность создать игру с разными уровнями сложности и характеристиками, и разными соперниками (онлайн/друг/бот)
  - Пользователь должен иметь возможность задать время игры
  - Пользователь должен иметь возможность выбрать задачу по названию или тегам
  - Пользователь должен иметь возможность выбрать язык для создания игры 
  - Пользователь должен иметь возможность проверить свое решение
  - Пользователь должен иметь возможность переподключения в игру в случае вылета из нее 
  - Пользователь должен иметь возможность общаться (чат)
non-functional:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Пользователь не может редактировать код соперника 
